name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Testes
        run: |
          PYTHONPATH=.
          pytest

      - name: Build
        run: |
          fastapi run app/main.py

      - name: Deploy (Exemplo)
        run: |
          echo "App no ar!"
