name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Testes
        run: |
          PYTHONPATH=. pytest

      - name: Build
        run: |
          PYTHONPATH=. fastapi run app/main.py &
          sleep 3
          curl -f http://127.0.0.1:8000/docs

      - name: Deploy (Exemplo)
        run: |
          echo "App no ar!"
